apiVersion: apps/v1
kind: Deployment
metadata:
  name: book-catalog-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: book-catalog
  template:
    metadata:
      labels:
        app: book-catalog
    spec:
      containers:
      - name: book-catalog
        image: sharique.azurecr.io/book_catalog:latest
        ports:
        - containerPort: 8000
        env:
        - name: PORT
          value: "8000"
        - name: DATABASE_URL
          value: postgresql://sharique_5blf_user:TJOmIqWEVSg81AOGZynPZe7kN4sFpi5E@dpg-crkktk68ii6s7381mcn0-a.oregon-postgres.render.com/sharique_5blf
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-management-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventory-management
  template:
    metadata:
      labels:
        app: inventory-management
    spec:
      containers:
      - name: inventory-management
        image: sharique.azurecr.io/inventory_management:latest
        ports:
        - containerPort: 8001
        env:
        - name: PORT
          value: "8001"
        - name: DATABASE_URL
          value: postgresql://sharique_5blf_user:TJOmIqWEVSg81AOGZynPZe7kN4sFpi5E@dpg-crkktk68ii6s7381mcn0-a.oregon-postgres.render.com/sharique_5blf
---
apiVersion: v1
kind: Service
metadata:
  name: book-catalog-service
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 4000
      targetPort: 8000

  selector:
    app: book-catalog
---
apiVersion: v1
kind: Service
metadata:
  name: inventory-management-service
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 4001
      targetPort: 8001
  selector:
    app: inventory-management
