version: '3.8'

services:
  book_catalog:
    image: sharique.azurecr.io/book_catalog:latest
    build: 
      context: ./book_catalog
      dockerfile: Dockerfile
    ports:
      - "4000:8000"
    environment:
      - PORT=8000
      - DATABASE_URL=postgresql://sharique_5blf_user:TJOmIqWEVSg81AOGZynPZe7kN4sFpi5E@dpg-crkktk68ii6s7381mcn0-a.oregon-postgres.render.com/sharique_5blf

  inventory_management:
    image: sharique.azurecr.io/inventory_management:latest
    build: 
      context: ./inventory_management
      dockerfile: Dockerfile
    ports:
      - "4001:8001"
    environment:
      - PORT=8001
      - DATABASE_URL=postgresql://sharique_5blf_user:TJOmIqWEVSg81AOGZynPZe7kN4sFpi5E@dpg-crkktk68ii6s7381mcn0-a.oregon-postgres.render.com/sharique_5blf


